### PR TITLE
Add install options to cmake

### PR DESCRIPTION
**Pull request by bwrsandman**
Set public include directories to build and installed options.
Add include to GNUInstallDirs to have correct install locations on linux.
Add config export options.
Add sx:: namespace to find package.

### CODE REVIEW

**Comment by bwrsandman** [comment]
Example of using installed namespace
---

```
cmake_minimum_required(VERSION 3.0)
project(using_sx)

find_package(sx REQUIRED)

add_executable(using_sx main.c)

target_link_libraries(using_sx PRIVATE sx::sx)
```

Installing on arch linux
---
```bash
cd "${srcdir}/${pkgname%-git}"
cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DSX_SHARED_LIB=ON \
      -DCMAKE_INSTALL_LIBDIR=/usr/lib \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo
make
make install
```

Installed files
```
/usr/lib/libsx.so
/usr/lib/cmake/sx/sx-config.cmake
/usr/lib/cmake/sx/sx-config-relwithdebinfo.cmake
/usr/include/sx
/usr/include/sx/_simd.h
/usr/include/sx/allocator.h
/usr/include/sx/array.h
/usr/include/sx/atomic.h
/usr/include/sx/bheap.h
/usr/include/sx/cmdline.h
/usr/include/sx/config.h
/usr/include/sx/fiber.h
/usr/include/sx/handle.h
/usr/include/sx/hash.h
/usr/include/sx/ini.h
/usr/include/sx/io.h
/usr/include/sx/jobs.h
/usr/include/sx/lin-alloc.h
/usr/include/sx/macros.h
/usr/include/sx/math.h
/usr/include/sx/os.h
/usr/include/sx/platform.h
/usr/include/sx/pool.h
/usr/include/sx/rng.h
/usr/include/sx/simd.h
/usr/include/sx/stack-alloc.h
/usr/include/sx/string.h
/usr/include/sx/sx.h
/usr/include/sx/threads.h
/usr/include/sx/timer.h
/usr/include/sx/tlsf-alloc.h
/usr/include/sx/virtual-alloc.h
```

**Comment by septag** [comment]
Thanks. the cmake changes seems nice.
But I'm not very familiar with the `namespace` stuff (`target_link_libraries(using_sx PRIVATE sx::sx)`). Does it break the existing projects that are using sx ?

**Comment by bwrsandman** [comment]
It depends if you're using the installed lib with `find_package(sx REQUIRED)` when it's installed which uses `sx-config.cmake`, then you need the namespace(`sx::`) and the component (`::sx`). This is so if you have another project in the lib, you can specify them i.e. `find_package(sx REQUIRED COMPONENTS sx sx_optional_component)`.

If your project is using sx with `add_subdirectory` then you have to use the name defined in `add_library` without namespace.

Existing projects will not be affected since they are probably not using `find_package`.
The namespace exists only in `/usr/lib64/cmake/sx/sx-config.cmake` which looks like this by the way:
```cmake
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget sx::sx)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# The installation prefix configured by this project.
set(_IMPORT_PREFIX "/usr")

# Create imported target sx::sx
add_library(sx::sx SHARED IMPORTED)

set_target_properties(sx::sx PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "dl;pthread;m"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/sx-config-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
```

**Comment by septag** [comment]
Nice. thanks

**Pull request merged**
